"""Editable, evidence-linked prose for the five SCADS research case studies.

All numeric claims come from the listed repository sources. Publication date is
October 7, 2026; experiment dates are stated only when needed and documented.
"""

PAPERS = [
{
 'number':'01','slug':'01-sensemaking','short':'ORGANIZATIONAL SENSEMAKING',
 'title':'Evidence across an organization',
 'subtitle':'An auditable agent workflow for organizational sensemaking',
 'refs':[
   ('Project overview and implemented system','README.md'),
   ('Riverwatch14 independent AI source review','examples/local-riverwatch-guidance-accepted/REVIEW.md'),
   ('Original Riverwatch14 report','examples/local-riverwatch-guidance-accepted/report.md'),
   ('Original run metadata','examples/local-riverwatch-guidance-accepted/run-metadata.json'),
   ('Frozen v12 reproduction instructions','evaluations/local-pilot/implementation-v12/README.md'),
   ('Source-package reproduction','docs/package-reproduction.md'),
   ('Evidence catalog contract','docs/evidence-catalog.md'),
 ],
 'pages':[
 {'title':'','blocks':[
   ('h','Abstract'),
   ('p','An organization is a collection of related teams, projects, records and external dependencies. A useful assessment must follow those relationships without turning every connected fact into a claim about the entire organization. This implementation equips an agent with six evidence tools, a directed graph, structured retrieval and direct media inspection. The agent chooses its investigative path and produces cited findings, qualifications and unresolved conflicts. [1]'),
   ('p','A recorded local-model investigation of the fictional Riverwatch project retrieved nine sources through 15 MCP calls and inspected an image plus sampled video frames. A separate AI source review accepted the bounded development case. The case demonstrates traceable tool use and careful treatment of competing claims; it is neither independent human validation nor a statistical estimate of reliability. [2-4]'.replace('[2-4]','[2] [3] [4]')),
   ('h','Problem and design objective'),
   ('p','The SCADS task concerns sensemaking for nonatomic entities: entities whose properties depend on connected parts. Evidence is distributed across representations, names can be ambiguous, and dates can disagree. The design objective is an inspectable path from an analyst question to source-supported conclusions, with the subject and evidential scope preserved at every step. [1]'),
   ('h','Implemented contribution'),
   ('p','The working contribution combines identity resolution, bounded relationship traversal, source retrieval, multimodal evidence access and a recorded synthesis workflow. A local llama.cpp model supplies the free execution path; an optional Codex harness uses the same MCP interface. A static case explorer exposes saved reports, sources and tool sequences for inspection without running inference. [1]'),
   ('note','Evidence class: authored synthetic investigation, recorded local inference, separate AI source review and deterministic software checks. The paper reports the implemented method and its observed behavior.'),
 ]},
 {'title':'1. Method and architecture','blocks':[
   ('p','The architecture separates decisions made by the model from evidence supplied by the host. The model selects tools and writes findings. Retrieval returns identified records and graph proofs; declared host fields provide the overview and run limitations. This distinction lets a reader inspect which statements were generated and which were assembled from verified run facts. [1] [2]'),
   ('table',['Stage','Operation','Preserved evidence'],[
      ['Resolve','entity_search','Canonical IDs and ambiguous alternatives'],
      ['Connect','traverse_relationships','Typed directed paths, depth and supporting sources'],
      ['Read','search_evidence + read_evidence','Full records, dates and locators'],
      ['Inspect','inspect_media + read_media','Availability, original pixels and decoded frame times'],
      ['Synthesize','Recorded agent run','Cited findings, conflicts, qualifications and trace'],
   ],[65,171,252]),
   ('p','Structured records are queried through SQLite; source text and supplied assertion triples are indexed locally. The graph is a directed JSON edge-list representation. Relationship expansion has a declared depth, and every relevant edge keeps its supporting source IDs. A dependency edge is distinct from organizational containment or managerial control. [1] [12]'),
   ('h','Retrieve before citing'),
   ('p','The bounded catalog exposes metadata pages for selective discovery. Discovering an evidence ID is not equivalent to reading the source. Inventory coverage and fully retrieved, citable evidence therefore have separate records. This reduces the chance that an agent cites a promising title as though it had inspected the underlying statement. [7]'),
   ('h','Reconcile rather than overwrite'),
   ('p','Competing assertions retain subject, date, predicate, value and provenance. A more recent record can suggest an update, but recency alone does not prove that an earlier assertion was corrected. Reports preserve unresolved differences, distinguish plans from observed events and label inferences. Repeated fixture content across media is shared-origin evidence, not independent corroboration. [1] [2]'),
   ('note','Figure 1. The table follows the implemented investigative sequence. It is a method diagram, not a claim that every run visits all stages or that the model follows a fixed script.'),
 ]},
 {'title':'2. Worked case: Riverwatch','blocks':[
   ('p','The fictional Cedar Basin Research Institute contains divisions, teams and projects. Riverwatch depends on the Silt Sensor Batch supplied by Northline Instruments. A register records readiness, later material records delay, and supplier records contain different expected-arrival dates. The task is to explain readiness and dependencies while keeping the conclusion scoped to Riverwatch. [1] [2]'),
   ('table',['Evidence pattern','Supported interpretation'],[
      ['September 3 ready register; September 5 delayed material','Retain the dated readiness disagreement; do not declare current truth from chronology alone.'],
      ['Riverwatch  ->  sensor batch  ->  Northline','Preserve the dependency and supply relations; the path does not establish organizational control.'],
      ['Expected arrival September 14; later September 19','These are planning claims. Neither establishes shipment or receipt.'],
      ['Pending acceptance and required calibration','Describe release conditions without asserting an exclusive cause or proving the sensors defect-free.'],
      ['PNG and video caption boards','Inspect actual pixels, while retaining their authored synthetic origin.'],
   ],[190,298]),
   ('p','The accepted report contains four findings and two conflicts. Its review checked the source IDs, values, dated disagreements, supplier path and uncertainty wording. Original report bytes were preserved; a cosmetic color description and imprecise shipping terminology remain disclosed in the review. The analysis still distinguished expected arrival from delivery. [2] [3]'),
   ('h','Media and absence'),
   ('p','The run inspected the supplied PNG and decoded video frames returned at 0, 15 and 29 seconds. Those are caption fixtures without audio. An inspection-tag annotation had no declared attachment; the tool reported unavailable pixels. Treating that absence explicitly is part of the result, rather than replacing it with a model-generated visual description. [2]'),
   ('note','The unrelated arts event mentioning Riverwatch was excluded. The final report did not propagate project-level concern to an institute-wide shutdown or infer supplier misconduct. [2]'),
 ]},
 {'title':'3. Recorded evidence and interpretation','blocks':[
   ('table',['Measure','Observed result','Interpretation'],[
      ['MCP calls / sources','15 / 9','One known synthetic investigation'],
      ['Agent actions','21','Includes finish checks, observations and synthesis'],
      ['Elapsed time','2,538.563 seconds','Shared CPU host; not an isolated speed benchmark'],
      ['Findings / conflicts','4 / 2','Counts do not establish factual reliability'],
      ['Separate source review','Accepted with caveats','AI review; no human-gold or held-out estimate'],
      ['Implementation checks','268 tests passed','Software behavior, separate from analytic acceptance'],
   ],[131,130,227]),
   ('p','Run counts, timing and review scope are preserved in the original metadata and review. The latest overview records the implementation test total separately. The local case used frozen implementation v12 and a pinned Qwen3.5-9B Q3_K_M configuration; later implementation checks do not retroactively change that execution. [1] [2] [4] [5]'),
   ('h','What the evidence supports'),
   ('p','The trace establishes that tools were actually called and that their returned records supported an inspectable investigation. The source review establishes that this particular report preserves the crucial distinctions in the authored case: unresolved readiness, a full supplier path, planned dates and nonexclusive explanations. Mechanical citation validation alone would not establish those semantic properties. [2]'),
   ('h','Scope of inference'),
   ('p','The corpus has ten entities, 16 authored evidence records and seven retrieval regression cases. Its image and video repeat authored information. This makes it useful for controlled behavioral inspection while restricting any inference about natural scenes, audio, source independence or organizational truth. The development case is known and tuned; its acceptance cannot estimate general performance on unseen organizations. [1] [2]'),
   ('p','The most useful result is methodological: uncertainty can remain attached to a claim even when the agent produces a concise answer. A readable answer and a detailed audit trail serve different purposes, and the implementation retains both. This interpretation follows the demonstrated case rather than claiming measured analyst-time savings.'),
 ]},
 {'title':'4. Reproducibility and sources','blocks':[
   ('p','Start at the project directory in the public source repository. The README provides dependencies, local-model setup and the static case explorer. To inspect the exact analytic result, begin with the original report, trace, ledger and run metadata; use the frozen v12 instructions when reproducing the accepted model configuration. [1] [2] [5]'),
   ('code','python sensemaking.py entities\npython sensemaking.py investigate riverwatch --max-hops 2\npython sensemaking.py evaluate\npython scripts/build_showcase.py'),
   ('p','The deterministic investigate command creates an evidence packet; it is not the end-to-end agent analysis. Media inspection requires the documented ffmpeg/ffprobe tools. The local inference path requires separately installed model assets. Source-package reproduction checks bind file hashes and viewer contents without treating a same-host extraction as independent model validation. [1] [6]'),
   ('h','Evidence-linked references'),('refs',),
   ('note','Citation links point to the nested project source. The publication evidence manifest records hashes of the source files used for this paper; editable prose and the PDF builder accompany the publication.'),
 ]},
 ]
},
{
 'number':'02','slug':'02-311-analytics','short':'NYC 311 ANALYTICS',
 'title':'A conversation backed by calculations',
 'subtitle':'Reproducible civic analytics through an agent-neutral tool service',
 'refs':[
   ('Implemented service and current version','README.md'),
   ('Analysis and artifact tool contract','docs/tool-contract.md'),
   ('Authored CLI demonstration results','examples/agent-demo/answer.md'),
   ('Generated 100,000-record measurements','examples/evidence/generated-100000-benchmark.json'),
   ('Version 0.6 focused verification receipt','examples/evidence/test-report-v0.6-focused.json'),
   ('Static scale review and version 0.6 changes','docs/forecast-v0.6.md'),
   ('Local runtime and ingestion instructions','docs/runtime.md'),
 ],
 'pages':[
 {'title':'','blocks':[
   ('h','Abstract'),
   ('p','Natural-language civic questions often hide analytical choices: date boundaries, complaint families, geographic units, cohort selection and missing values. This implementation places those choices in a strict analytical contract. A compatible agent handles conversation, while a Python service owns validation, deterministic calculations, saved results and derived artifacts. The same operations are available through JSON CLI and seven MCP tools. [1] [2]'),
   ('p','The service implements record filtering, grouped statistics, geographic predicates, period comparisons and background CSV exports, with Elasticsearch and Kibana adapters. Its local demonstration uses 32 authored synthetic requests. This case study reports that demonstration, historical generated-data measurements and the focused engineering verification for version 0.6.0. These evidence classes are kept separate. [1] [3-5]'.replace('[3-5]','[3] [4] [5]')),
   ('h','Problem and design objective'),
   ('p','The SCADS problem asks for conversational access to large civic datasets. The design objective is to make the analytical answer inspectable and reusable across agents: every reported number should resolve to a saved specification, dataset identity and result. A small preview must not silently redefine an export, and an uncovered date must not become a zero-count day. [1] [2]'),
   ('h','Implemented contribution'),
   ('p','The core contribution is a provider-neutral analytical boundary. The model need not implement arithmetic, invent query semantics or carry an entire result table in context. Version 0.6 adds bounded normalization, exact export admission and requested-field retrieval, grounded in a static scale review rather than a newly executed scale experiment. [1] [6]'),
   ('note','Evidence class: synthetic fixture analyses, generated local workload observations and focused deterministic tests. One billion records is a design target, not a measured capacity result. [1]'),
 ]},
 {'title':'1. Analytical contract','blocks':[
   ('p','A request selects records, aggregate or compare_periods and binds that operation to a dataset version. Filters can express bounded Boolean predicates, category families, geographic regions and explicit time intervals. Unsupported combinations return a typed error instead of a silently simplified query. [2]'),
   ('table',['Phase','Service responsibility'],[
      ['Discover','Return the catalog, field meanings, coverage, limits and supported request examples.'],
      ['Validate','Resolve absolute time boundaries, check schema and reject unsupported or uncovered analyses.'],
      ['Execute','Compute the selected records or aggregates and save normalized specification, dataset identity and execution flags.'],
      ['Inspect','Return bounded pages with exact matching totals and explicit truncation or approximation.'],
      ['Publish artifact','Derive CSV or map from the saved cohort; retain scope, excluded geography and artifact hashes.'],
   ],[100,388]),
   ('h','Time, rates and missingness'),
   ('p','Time intervals are start-inclusive and end-exclusive. Relative presets resolve through a shared timezone library and are saved as absolute boundaries. Period comparisons use the same non-time filters and grouping domain; they report counts, exposure days, daily rates, absolute differences and nullable relative change. Complete creation-date coverage is required for both periods. [2]'),
   ('p','Closure duration measures administrative created-to-closed time, not time to first response or verified resolution. Missing usable durations remain null and are excluded from duration statistics while closed-request counts retain those records. A null value therefore cannot be interpreted as zero hours. These definitions travel with results instead of depending on the agent to recall them. [2] [3]'),
   ('h','Artifacts retain analytical scope'),
   ('p','CSV and map tools consume a saved result ID. They require an explicit all-matching or selected-groups scope. A records export reproduces the full selected cohort rather than the preview. Version 0.6 checks exact planned rows before reserving a worker and limits backend source retrieval to selected CSV fields while retaining selection and ordering semantics. [2] [6]'),
 ]},
 {'title':'2. Worked fixture analysis','blocks':[
   ('p','The authored demonstration interprets Brooklyn noise last month relative to January 2, 2026. The saved window is December 2025 in America/New_York. It finds four matching synthetic requests, previews two and exports all four. The example shows why preview size and cohort size must be different fields. [3]'),
   ('table',['Question','Observed fixture result','Meaning'],[
      ['December Brooklyn noise','4 requests; 2-row preview; 4-row CSV','Export preserves full selection.'],
      ['November-December rodent comparison','17 requests across 6 groups','Rates use 30 versus 31 days.'],
      ['Brooklyn DOHMH closure','7 requests; 6 closed; mean 31.2 h','Mean uses 5 usable durations.'],
      ['Brooklyn NYPD closure','7 requests; 5 closed; mean 3.6 h','Different request mixes prevent causal comparison.'],
   ],[158,160,170]),
   ('h','Why unchanged counts can have changed rates'),
   ('p','A fixture neighborhood with one request in each month has November rate 1/30 and December rate 1/31 requests per day. December minus November is -0.0010752688 requests per day. The count is unchanged; exposure differs. This arithmetic is descriptive reported-request activity, not incident prevalence, statistical significance or a causal effect. [3]'),
   ('h','Unknown is an analytical result'),
   ('p','The same demonstration asks for January-February 2026 rodent trends, outside the fixture coverage. The service returns coverage_gap rather than filling unobserved dates with zeros. The behavior protects the meaning of a comparison before any model-generated narrative is written. [3]'),
   ('p','Neighborhood labels in this demonstration are explicitly synthetic. Real neighborhood analyses require versioned official geometry and a defined assignment policy. A map of underlying complaint points is also analytically different from a neighborhood trend layer; the artifact contract preserves that distinction. [2] [3]'),
   ('note','Table 1. All numerical results on this page describe the 32-record fixture. They are not findings about actual New York City residents or agencies.'),
 ]},
 {'title':'3. Engineering evidence','blocks':[
   ('table',['Evidence','Recorded result','Scope'],[
      ['Version 0.6 focused checks','119 passed; no failures, errors or skips','Selected deterministic checks; tiny authored records and fake transports. [5]'],
      ['Generated local workload','100,000 rows; 3 runs','Fixture backend, 15 returned groups per run. [4]'],
      ['Historical run times','13.0741, 4.5881, 15.2276 s','Median 13.0741 s; cache states uncontrolled. [4]'],
      ['Current scale review','Static reasoning and implementation','No scale simulation or live engine run for v0.6. [6]'],
   ],[139,143,206]),
   ('p','The historical generated workload exercised tool execution, not model latency or natural-language accuracy. With only three runs and uncontrolled caches, its maximum is an observed maximum rather than a stable tail-latency estimate. The fixture backend cannot establish Elasticsearch or Kibana capacity. [4]'),
   ('h','Resource-aware implementation'),
   ('p','Version 0.6 limits normalization output bytes, checks observed free disk, uses portable UTF-8/LF output and records limits in the manifest. Known oversized CSV cohorts are rejected before worker admission. Streaming row, byte, deadline and source-identity guards remain active after admission: a planned row count is not a promise of successful completion. [2] [6]'),
   ('h','Interpretation'),
   ('p','These results support a narrower but useful conclusion: analytical semantics can be implemented independently of an agent and tested through inspectable inputs and outputs. The worked example verifies distinctions that conversational systems often blur, including missing durations, full cohorts, exposure-normalized rates and date coverage. It does not estimate how often an arbitrary agent chooses the correct specification.'),
   ('p','The service defines a path from small local fixtures to self-hosted indexing. Its capacity claims remain tied to the measured backend and workload. Real-city analytical validity requires a qualified immutable dataset and independent reference answers; the synthetic numbers presented here are deliberately interpreted only within their authored environment. [1] [3]'),
 ]},
 {'title':'4. Reproducibility and sources','blocks':[
   ('p','The README and runtime guide describe installation, dataset configuration, ingestion and MCP connection. Begin with the local fixture before selecting an external backend. Use describe_dataset to obtain the current catalog and request rules; save the returned result identity before deriving artifacts. [1] [7]'),
   ('code','python -m pip install -e ".[mcp,geo]"\npython -m analytics311 doctor\npython -m analytics311 run examples/brooklyn-noise.json\npython -m analytics311 mcp'),
   ('p','Commands run from the nested project directory in an appropriate Python environment. The bundled fixture operates locally after dependency installation. The original authored demonstration includes its CLI trace, request specifications and exported CSV fingerprint. The v0.6 focused receipt identifies its source/test selection; it should be read as focused verification for that version. [1] [3] [5]'),
   ('h','Evidence-linked references'),('refs',),
   ('note','The PDF summarizes retained source records; publication did not rerun the historical benchmark or launch a live Elasticsearch workload. Refer to the evidence manifest for source hashes.'),
 ]},
 ]
},
{
 'number':'03','slug':'03-semantic-discovery','short':'TECHNICAL DOCUMENT DISCOVERY',
 'title':'Search the released knowledge',
 'subtitle':'Offline technical-manual discovery across a controlled metadata boundary',
 'refs':[
   ('Implemented system and architecture','README.md'),
   ('Extraction development diagnostics','reports/extraction-development.md'),
   ('Retrieval development evaluation','reports/retrieval-development.md'),
   ('Guided interface verification','reports/interface-verification.md'),
   ('Build and portable-runtime verification','reports/build-verification.json'),
   ('Operating and reproduction guide','RUNBOOK.md'),
   ('Measured acceptance and evidence scope','reports/acceptance-status.md'),
 ],
 'pages':[
 {'title':'','blocks':[
   ('h','Abstract'),
   ('p','Technical discovery has two distinct tasks: interpreting a scanned manual and searching what is permitted to leave the source workspace. Vintage Overseas Power Tools (VOPT) implements both as an offline pipeline. Original PDFs, OCR and evidence remain private to extraction and review; discovery receives a validated metadata snapshot with either coverage or approved values. [1]'),
   ('p','The development corpus contains five admitted historical manuals and 616 pages. Layout-aware rules matched 13 of 17 selected reference fields, compared with four for a line baseline. Retrieval over reviewed values recorded recall@10 of 0.912 on 17 authored positive queries. These are development diagnostics with agent-inspected references, not held-out accuracy or human-gold estimates. [2] [3]'),
   ('h','Problem and design objective'),
   ('p','The SCADS task asks for technical attribute extraction from scanned documentation and natural-language document discovery. The implemented objective is discovery with inspectable constraints: identify the relevant document and model without inventing values or leaking source content into the released index. Numerical filtering requires released values; coverage-only metadata can establish that a topic is covered but cannot satisfy a threshold. [1]'),
   ('h','Implemented contribution'),
   ('p','A private extraction workspace, append-only review, strict release profiles and a separate discovery process form the core. The query compiler preserves model, variant, units and conditions. A guided Equipment  ->  Specification  ->  Results interface helps users express the bounded grammar while exposing unknowns and partial processing. [1] [4]'),
   ('note','Evidence class: authentic historical scans used during development; agent-reviewed observations; authored queries; local packaging and interface verification. Source interpretation and retrieval are evaluated separately.'),
 ]},
 {'title':'1. Architecture and release boundary','blocks':[
   ('table',['Workspace','Implemented method','Output'],[
      ['Extraction','PyMuPDF geometry/native text; local RapidOCR ONNX for image pages','Page records, model-scoped candidates and evidence coordinates'],
      ['Review','Append-only decisions bound to extraction fingerprints','Accepted/corrected assertions with reviewer provenance'],
      ['Release','Field allowlists and separate coverage/value profiles','Validated versioned metadata bundle'],
      ['Discovery','SQLite, exact predicates and BM25; TF-IDF comparator','Ranked document/model scopes and request references'],
   ],[79,225,184]),
   ('p','Every candidate must preserve document revision, model, attribute, value or range, unit and rating/operating qualifiers. A correctly read number can still be attached to the wrong component or configuration. Review therefore examines factual scope rather than treating OCR confidence as a probability that a specification is true. [1] [2]'),
   ('h','Coverage is a separate product'),
   ('p','Coverage exports describe verified attribute presence. Value exports may additionally include approved typed values and conditions. A coverage query such as which manuals discuss voltage differs from a request for equipment above a voltage threshold. The discovery service rejects unsupported numeric filtering under a coverage-only profile rather than dropping the constraint. [1] [5]'),
   ('h','Exact predicates precede ranking'),
   ('p','The query plan is inspectable: identifiers, attribute roles, operators, units, Boolean structure and conditions are explicit. Hard predicates enforce same-model and compatible-variant scope before ranking. BM25 is the default ranker. The semantic comparator is ontology-normalized TF-IDF, not a pretrained embedding system. Both share the same predicate compiler. [1] [3]'),
   ('p','Atomic catalog import and full index replacement support controlled release changes. Review and extraction fingerprints detect stale decisions, while monotonic withdrawal handling prevents a rollback from simply restoring removed metadata. The separate discovery installation has neither source files nor extraction dependencies in its verified profile. [1] [5] [7]'),
 ]},
 {'title':'2. Worked discovery: HR-28','blocks':[
   ('p','A verified browser journey asks for model HR-28 with output power at least 1.4 kW, output voltage at least 30 V and DC operation. The guided interface returns one confirmed match in the Homelite manual, along with the partial-processing notice. Supporting assertion IDs and the source revision remain attached to the request reference. [4]'),
   ('table',['User intent','Interpretation','Observed behavior'],[
      ['Generator manuals covering output voltage','Coverage; no threshold','M7 and HR-28 confirmed; incomplete scopes shown separately.'],
      ['Output voltage at least 125 V','Value constraint','No confirmed matches; six records require more detail.'],
      ['HR-28, >=30 V, >=1.4 kW, DC','Same model and compatible conditions','One confirmed match with provenance and partial-processing notice.'],
      ['Voltage above 100 V','Input/output role ambiguous','Clarification required.'],
   ],[151,154,183]),
   ('p','This example illustrates why model and qualifier association matter more than matching a keyword. Input voltage is not output voltage, and electrical input power must not become mechanical output power through a unit conversion. A compendium containing several models cannot satisfy a conjunction by joining one model\'s voltage to another model\'s power. [1] [4]'),
   ('h','A request, not an invented document answer'),
   ('p','The exported JSON stores a document/version reference, catalog identity, query and supporting assertion IDs. A verified journey saved HR-28 from a coverage query, then ran a different numeric query; the actual downloaded request still retained the originating query. It contained released metadata rather than original PDF or OCR content. [4]'),
   ('h','Unknowns remain visible'),
   ('p','An unobserved field means unknown, not absent or zero. Partial page processing is retained with matches, and ambiguous operating conditions are not converted into broad ranges. A discovery result therefore describes what the approved catalog can support, while document acquisition remains a separate action. [1] [3] [4]'),
   ('note','Table 1. These are agent-operated browser checks on the frozen development catalog. They verify specific interface behavior, not independent usability or generalized extraction accuracy. [4]'),
 ]},
 {'title':'3. Development results','blocks':[
   ('table',['Measure','Observed value','Denominator / scope'],[
      ['Admitted scans','5 manuals; 616 pages','610 processed pages; 6 explicit failures. [2]'],
      ['Selected field matches','Layout 13/17; line 4/17','Document, page, model, attribute, unit, value and qualifier. [2]'],
      ['Reviewed-values retrieval','Macro recall@10 0.912; macro MRR@10 0.941','17 positive authored queries; 22 known scopes. [3]'],
      ['Reference-values retrieval','Macro recall@10 1.000; macro MRR@10 1.000','Same known positives; diagnostic reference metadata. [3]'],
      ['Plan status checks','33/33','Authored source-reference queries. [3]'],
      ['Recorded regression suite','151 passed','Build-verification snapshot; separate from later UI checks. [5]'],
   ],[136,151,201]),
   ('p','Selected field matches are not exhaustive recall or full-assertion precision. The extraction report notes that conditions and component meaning need additional review. The retrieval reference condition is also deliberately separate from reviewed extraction: perfect reference-metadata retrieval cannot conceal omissions in the actual catalog. Both rankers produced equal reported results in these development comparisons. [2] [3]'),
   ('h','An informative failure distinction'),
   ('p','A preserved first M18 audit supported all 17 numeric transcriptions but only five candidates with essential factual scope. Nine needed scope repair and three named the wrong entity. A repaired seven-candidate record was source-inspected as supported, but suppressed observations and a known development manual prevent a recall or generalization claim. The lesson is that number recognition and technical truth are different evaluation targets. [2]'),
   ('h','Offline evidence'),
   ('p','The recorded portable discovery and extraction profiles cold-started on the existing Windows host using packaged assets, with Python network attempts blocked. Discovery operated without private source files. These checks support the tested packaging boundary; they are not OS-level network isolation or independent clean-target certification. [5]'),
 ]},
 {'title':'4. Reproducibility and sources','blocks':[
   ('p','Use the operating guide for the private extraction/review and released discovery workflows. Frozen evaluation records preserve the processing versions that produced them; do not silently reprocess them and present new results as the original experiment. Source and review provenance are part of the research artifact. [6] [7]'),
   ('code','python -m vopt doctor\npython -m pytest -q\npython scripts/evaluate_extraction.py --skip-ingest'),
   ('p','Run these commands from the environment described in the implementation guide and RUNBOOK. Exact historical extraction replay requires the separately retained frozen runs/real-workspace or research-evidence bundle; a Git-only checkout is not a self-contained copy of that workspace. Fresh corpus acquisition and OCR constitute a new run. For discovery reproduction, use a versioned released catalog and inspect its query plan. Package hashes and later UI checks identify their respective snapshots. [1] [4-6]'.replace('[4-6]','[4] [5] [6]')),
   ('h','Evidence-linked references'),('refs',),
   ('note','Publication reproduces recorded measurements, not a new OCR evaluation. No human-gold, untouched-family, labor-savings or classified-deployment claim is made.'),
 ]},
 ]
},
{
 'number':'04','slug':'04-org-knowledge-graphs','short':'ORGANIZATIONAL KNOWLEDGE GRAPHS',
 'title':'An organization chart with evidence',
 'subtitle':'Conservative relationship inference and navigable organizational knowledge',
 'refs':[
   ('Implemented workbench and synthetic corpus','README.md'),
   ('Canonical data and API contract','docs/implementation-contract.md'),
   ('Recorded software and browser verification','docs/verification.md'),
   ('10,000-person communication-corpus result','docs/synthetic-10000-results.json'),
   ('Synthetic storage benchmark','docs/benchmark-results.json'),
   ('Inference research and evaluation distinctions','research/inference.md'),
   ('Completion evidence and acceptance scope','docs/acceptance.md'),
 ],
 'pages':[
 {'title':'','blocks':[
   ('h','Abstract'),
   ('p','Communication records can suggest authority, collaboration and membership, but these are different relationships. This workbench keeps their types and provenance separate while building an inspectable organization graph. The implementation combines staged intake, conservative local inference, immutable SQLite snapshots, reversible analyst review and a React interface with bounded semantic zoom. [1] [2]'),
   ('p','A deterministic synthetic corpus with 10,000 people and 76,680 messages was imported and analyzed in a recorded local run. It produced 7,489 selected reporting links and retained 2,511 unresolved people. Read-only traversal reached every person through formal and inferred groupings. These results demonstrate workflow and navigability on authored data, without treating raw scores as probabilities or generated labels as independent accuracy evidence. [3] [4]'),
   ('h','Problem and design objective'),
   ('p','The SCADS problem concerns deriving organizational knowledge from partial evidence and supporting exploration as the graph grows. The implemented objective is to preserve the distinction between what a source states, what the baseline infers and what an analyst reviews. A visually complete tree must not conceal unresolved managers or convert communication frequency into direct supervision. [1] [2] [6]'),
   ('h','Implemented contribution'),
   ('p','The working system integrates evidence spans, typed authority relations, sparse candidate generation, revision-aware review and scalable navigation. Intake profiles the proposed corpus before saving it. The graph can be explored through departments, communication groups, reporting branches and individual connections without drawing every person at once. [1] [2]'),
   ('note','Evidence class: fictional communications and source hierarchies, engineering checks and recorded local timings. Ranking scores are explicitly uncalibrated; synthetic labels are excluded from inference inputs.'),
 ]},
 {'title':'1. Inference and durable review','blocks':[
   ('table',['Layer','Implemented responsibility'],[
      ['Intake','Parse canonical JSON, message/roster CSV and mail formats; profile quality and preview a bounded source graph.'],
      ['Inference','Generate sparse candidates from communications and explicit self-report language; retain unresolved people.'],
      ['Evidence','Keep message spans, communication aggregates, source assertions and analyst references distinct.'],
      ['Persistence','Store immutable snapshots, durable jobs and append-only review events in SQLite.'],
      ['Exploration','Serve snapshot-bound pages and bounded graphs through FastAPI to React/TypeScript.'],
   ],[90,398]),
   ('p','The canonical assertion includes subject, relation, object, origin, evidence IDs, review status and temporal bounds. Primary and matrix reporting can be represented separately. Raw scores and calibration status are distinct fields, and a reviewed replacement does not acquire a model probability merely because it appears in the same chart. [2]'),
   ('h','Isolate labels from inference'),
   ('p','The inference service strips evaluation labels, existing assertions and source evidence before sending entities and messages to its baseline engine. The fixture labels can describe authored structure without becoming hidden inputs. This is necessary for a meaningful software check, although shared organization and language templates still limit any accuracy interpretation. [1] [2] [4]'),
   ('h','Review is a versioned action'),
   ('p','Accept, reject, replace and undo operations require the current workspace revision and preserve their history. Rejecting a relation continues to matter across refreshed inference. Exported canonical packages can preserve historical projections and evidence; package restoration requires an empty workspace. Snapshot comparison evaluates semantic relationships instead of merely comparing assertion IDs. [2] [3]'),
   ('p','Intake inspection is staged in memory before an explicit build. The preview reports accepted records, missing-field coverage and a bounded source graph. It does not portray imported proposals as established authority. Exact inventory counts and visible processing stages let a user understand what will be saved. [2] [3]'),
 ]},
 {'title':'2. Worked exploration journey','blocks':[
   ('p','The synthetic entry path defaults to 10,000 people. Its reviewed preview measured 76,680 messages, 45 units, two shared mailboxes and 60,657 directed communication links. Evaluation labels remained separate. The workflow draws inspect  ->  profile  ->  plan  ->  database  ->  infer  ->  ready; explanatory replay is labeled and does not perform another inference run. [3]'),
   ('table',['Interaction','Recorded behavior','Analytical purpose'],[
      ['Enter a department','Move from aggregate scope to reporting branches','Keep organization-wide navigation readable.'],
      ['Focus a person','Display selected manager, alternatives and evidence','Connect the chart to its claims.'],
      ['Continue zooming','Expand from 29 to 79 to 199 links','Reveal context without shifting existing card positions.'],
      ['Inspect a reporting marker','Show source/model origin and review/calibration state','Avoid reading visual certainty as statistical confidence.'],
      ['Return to a prior scope','Restore camera and expanded context','Preserve the analyst\'s place in the investigation.'],
   ],[114,196,178]),
   ('h','Bound the display, preserve reachability'),
   ('p','The interface retains a rolling metadata window of at most 240 cards and renders at most 200 nearby cards. A bounded response cache supports return navigation. Reporting branches are presentation groups derived from selected links, not new formal teams. Explicit unassigned buckets keep unresolved people reachable. [1] [3]'),
   ('p','Read-only traversal of the live synthetic snapshot reached all 10,000 people through both chart lenses: 476 formal scopes over 501 pages, and 1,077 inferred scopes over 1,082 pages. Edge closure was checked so every displayed link referred to displayed people. These are coverage and consistency observations rather than browser frame-rate measurements. [3]'),
   ('note','Figure 1. The interaction sequence reflects recorded browser checks. Formal units, inferred communication groups and reporting branches remain differently labeled throughout the journey. [3]'),
 ]},
 {'title':'3. Recorded measurements','blocks':[
   ('table',['10,000-person communication run','Observed value'],[
      ['Messages / entities','76,680 / 10,047'],
      ['Generation / import','0.711 s / 9.199 s'],
      ['Inference and publication','46.979 s'],
      ['Selected / unresolved people','7,489 / 2,511'],
      ['Formal and inferred groups','107'],
   ],[279,209]),
   ('p','These values describe one local Windows run, with source and corpus fingerprints preserved. The synthetic generator uses deterministic templates and authored labels; the outcome is not an accuracy, calibration or unlabeled-transfer result. Unresolved people are an explicit output rather than nodes forced into a complete tree. [4]'),
   ('table',['Separate source-only benchmark','10,000 mixed','100,000 mixed'],[
      ['Import','2.749 s','77.945 s'],
      ['List page warm p95','27.311 ms','120.228 ms'],
      ['Substring search warm p95','45.378 ms','754.730 ms'],
      ['Focused graph warm p95','40.723 ms','42.893 ms'],
   ],[258,115,115]),
   ('p','The second table measures Python/SQLite reads on source-only hierarchies, using seven warm repetitions and a 200-node graph budget. Its nearest-rank p95 is descriptive for that small sample; caches were not flushed. HTTP, browser rendering, dense communication processing and inference quality are outside this benchmark. [5]'),
   ('h','Verification and interpretation'),
   ('p','The recorded current intake build passed 144 Python tests, 99 frontend checks and the production build. Browser verification covered source preview, saved-workspace reuse, isolated import/build, cancellation and responsive layout. The evidence supports a durable, inspectable workflow and bounded navigation; it does not establish that communications reveal real managerial authority with calibrated confidence. [3] [7]'),
 ]},
 {'title':'4. Reproducibility and sources','blocks':[
   ('p','Use a separate database for each reproduced corpus. The default small fixture offers a quick review/export workflow; the deterministic generator also supports the documented 10,000-person case. Save source fingerprints and record environment and load when comparing timings. [1] [4]'),
   ('code','python -m orggraph demo --people 10000 --output runs/demo/corpus.json --generate-only\npython -m orggraph --db runs/demo.sqlite3 demo --people 10000\npython -m pytest -q\nnpm --prefix frontend test'),
   ('p','Run from the nested project directory after the documented dependency setup. The benchmark script and raw result file specify workload shapes, read methods and cache assumptions. The verification report links the browser evidence and distinguishes successive software milestones; test totals should always be attributed to the corresponding snapshot. [1] [3] [5]'),
   ('h','Evidence-linked references'),('refs',),
   ('note','No raw score is presented as a probability. Software tests, graph reachability, storage timing and real-world inference quality remain separate quantities in this publication.'),
 ]},
 ]
},
{
 'number':'05','slug':'05-graphrag-discovery','short':'TEMPORAL GRAPHRAG DISCOVERY',
 'title':'What changed, and when did we know?',
 'subtitle':'Local graph-assisted discovery with temporal provenance',
 'refs':[
   ('Current application and execution policy','README.md'),
   ('Implemented retrieval, history and interface','docs/implementation-status.md'),
   ('Authored temporal pump fixture','fixtures/pump/README.md'),
   ('Expected temporal states and comparisons','fixtures/pump/gold.json'),
   ('Actual local-model and vector smoke test','docs/local-model-validation.md'),
   ('Installation and package reproduction','docs/installation.md'),
   ('Temporal design and comparison semantics','docs/temporal-workflow.md'),
 ],
 'pages':[
 {'title':'','blocks':[
   ('h','Abstract'),
   ('p','A new search result can reflect a changed world, a late-arriving document, a correction or a different ranking. This GraphRAG discovery application preserves those distinctions through immutable source history, published knowledge snapshots, assertion validity intervals and saved baselines. It runs locally with a Python/SQLite core, a browser workspace and optional llama.cpp extraction and embeddings. [1] [2]'),
   ('p','A five-batch fictional pump history exercises plans, late corrections, conflicts and withdrawal. Its authored expectations specify eight historical states and two fixed-knowledge comparisons. A separate actual local-model smoke test extracted two source-grounded assertions and indexed three vectors. These are temporal consistency and integration observations, not a retrieval-quality or scale benchmark. [3-5]'.replace('[3-5]','[3] [4] [5]')),
   ('h','Problem and design objective'),
   ('p','The SCADS problem motivates discovery over connected evidence as a corpus changes. The implemented objective is to make each finding inspectable at a selected knowledge and world-time scope. A relationship must retain its source version and exact passage, while a baseline comparison must survive changes in top-ranked search results. [1] [2] [7]'),
   ('h','Implemented contribution'),
   ('p','The working system combines lexical, exact dense, hybrid and graph-assisted retrieval with eligibility checks before scoring. It saves investigations and scoped baselines, supports source-linked graph exploration and exports verifiable evidence bundles. Typing previews are a separate bounded keyword path that highlights evidence without calling a model or replacing committed results. [1] [2]'),
   ('note','Evidence class: manually authored temporal expectations, actual local-model development smoke tests and fixture/interface verification. Local inference uses no paid API dependency.'),
 ]},
 {'title':'1. Method: provenance before scoring','blocks':[
   ('table',['Concern','Implemented representation'],[
      ['Source identity','Immutable revisions, exact UTF-8 hashes and Unicode code-point spans'],
      ['System knowledge','Separate source availability, receipt, preparation and atomic publication'],
      ['World claims','Half-open validity intervals, known/open/unknown bounds and reported/planned/negated modality'],
      ['Retrieval','Lexical scoring, exact cosine, reciprocal-rank fusion and bounded graph expansion'],
      ['Comparison','Saved findings or fixed neighborhood seeds, paired before/after evidence and scoped coverage'],
   ],[113,375]),
   ('p','Eligibility is established before vector scoring. An index cannot justify retrieving future evidence into an earlier knowledge view. Immutable vector artifacts bind profile and text hashes; missing eligible vectors fail explicitly. The graph mode expands assertion seeds within declared candidate, hop and evidence limits. [2]'),
   ('h','Extraction is a proposal boundary'),
   ('p','The local model proposes assertions. The client validates exact quotations and endpoint mentions, creates mention-scoped identities and stages proposals before publication. Unknown dates remain unknown unless explicitly supported. Exact-span validation establishes mechanical grounding, while semantic correctness still depends on what the quoted language actually means. [2] [5]'),
   ('h','Three different comparisons'),
   ('p','A saved baseline can track selected findings or a fixed entity neighborhood. Knowledge comparisons inspect newly available support, corrections and withdrawals. Fixed-knowledge world comparisons hold the evidence cutoff constant while changing the claimed validity time. These answer different questions: what was learned versus what the sources say happened. [2] [7]'),
   ('p','The implementation uses SQLite and exact vectors. Its limits are explicit guardrails rather than benchmarked capacity promises. A displayed neighborhood is a bounded evidence projection, and a net comparison concerns endpoint states in its declared scope; neither implies semantic completeness over the corpus. [2]'),
 ]},
 {'title':'2. Worked temporal history','blocks':[
   ('p','The authored Pump P case uses controlled clocks and explicit one-operator-at-a-time semantics. Every assertion endpoint and interval is stated in its source sentence. The fixture isolates the difference between planned, reported, conflicting and withdrawn support. [3]'),
   ('table',['Published batch','Evidence meaning','Correct interpretation'],[
      ['January 5','A operates Pump P from January 1','Reported A, with no stated end.'],
      ['January 20','Plan: A ends and B starts February 1','Passing February 1 does not confirm B.'],
      ['February 10','Late correction: handover occurred February 3','Availability February 4 differs from receipt/publication February 10.'],
      ['February 12','Independent report names C from February 3','B and C coexist as disputed claims under fixture exclusivity.'],
      ['February 15','C source withdrawn','B support survives; withdrawal is not a physical handover.'],
   ],[93,186,209]),
   ('h','The same world date, different knowledge'),
   ('p','At a February 5 knowledge cutoff, the February 2 world-time view returns B as planned. At a February 11 cutoff, the corrected retrospective February 2 view returns reported A. The question\'s world date has not changed; the available evidence has. At the February 3 boundary, the later corrected history returns B because validity intervals are half-open. [4]'),
   ('h','Compare without future leakage'),
   ('p','Holding knowledge fixed at the February 10 publication allows a reported A-to-B comparison between January 31 and February 4. Holding knowledge fixed at the January 20 publication produces a planned transition instead. The later correction must not leak into the earlier answer. [4]'),
   ('note','Table 1. All dates and operator claims are fictional test values. The expected-state file was manually specified rather than generated from engine outputs; agreement tests authored semantics, not an actual pump history. [3] [4]'),
 ]},
 {'title':'3. Local-model and software evidence','blocks':[
   ('table',['Recorded observation','Value / result','Interpretation'],[
      ['Local extraction source','73 authored characters','Two simple fictional sentences.'],
      ['Validated assertions','2: reported and planned','Exact spans; unknown dates retained.'],
      ['Extraction/publication/query','29.39 s','One local run, excludes model startup.'],
      ['Vector index','3 vectors  x  2,048 components','One source chunk and two assertions.'],
      ['Vector-phase elapsed','2.44 s','Excludes restart/loading; integration smoke.'],
      ['Version 0.3.2 checks','138 Python + 30 frontend','Fixture and interface behavior.'],
   ],[161,158,169]),
   ('p','The actual local source states that Mira Labs operates Harbor Station and plans to lease Willow Annex. Qwen3-VL-2B-Instruct Q4_K_M through a dedicated llama.cpp server produced two grounded proposals. The queries preserved reported versus planned modality and null temporal bounds. Eight extraction-phase checks and eight vector-phase checks were recorded. [5]'),
   ('p','An initial embedding request on the chat-configured server returned HTTP 501; that attempt is preserved. After a separate embedding/pooling configuration, real vectors and query embeddings supported hybrid and graph queries with source-resolving exports. The same decoder weights demonstrate integration only; three exact-index rows do not establish semantic ranking quality or approximate-nearest-neighbor performance. [5]'),
   ('h','Interactive evidence without hidden inference'),
   ('p','The version 0.3.2 preview debounces typing for 300 ms and uses a separate bounded keyword/prefix endpoint. It creates no model calls or saved runs. Stale responses cannot replace newer scope or committed analysis; Escape, clearing or pausing restores the previous evidence state. Recorded desktop and 390  x  844 mobile checks exercised source tracing and restoration. [2]'),
   ('p','The evidence supports a reproducible local system that makes temporal and source distinctions visible. Whether graph expansion improves discovery over lexical or hybrid retrieval remains a separate empirical question; this publication reports no comparative quality uplift. [1] [2]'),
 ]},
 {'title':'4. Reproducibility and sources','blocks':[
   ('p','The authored demo needs only the application runtime and creates a new database, report and evidence bundles. Use fresh paths: the demo refuses to overwrite existing output. Local extraction and embeddings require the separately configured llama.cpp model service documented in the source. [1] [2] [6]'),
   ('code','python -m graphrag_discovery --db runs/demo.sqlite3 demo --output runs/demo\npython -m graphrag_discovery --db runs/demo.sqlite3 serve --port 8765\npython -m unittest discover -s tests -v'),
   ('p','Run from the nested project directory or an installed environment. The service binds to loopback; the authored demo uses simulated time and does not make model requests. Wheel/sdist installation instructions distinguish the application from separately installed model assets. Evidence bundles preserve source spans and hashes for inspection. [2] [6]'),
   ('h','Evidence-linked references'),('refs',),
   ('note','The static publication does not execute new model or performance experiments. Recorded development observations, authored temporal semantics and measured software behavior remain explicitly separate.'),
 ]},
 ]
}
]
