"""Projected solutions for SCADS Projects 6-9. No implementation/results claims.

Authored October 7, 2026. Numeric budgets, sample counts and thresholds below are
proposed design choices to preregister, not empirical observations.
"""

def p(text): return ('p', text)
def h(text): return ('h', text)
def note(text): return ('note', text)
def table(headers, rows, widths): return ('table', headers, rows, widths)
def page(title, *blocks): return {'title': title, 'blocks': list(blocks)}

PROPOSALS = [{
 'number':'06', 'slug':'06-agentic-retrieval', 'short':'BOUNDED AGENTIC RETRIEVAL',
 'title':'From a talk to a traceable dossier',
 'subtitle':'A projected agentic retrieval method for predetermined public resources',
 'refs':[
  ('SCADS 2026 Problem Book, Project 6, p. 8. User-supplied research brief.', None),
  ('Yao et al. (2023). ReAct: Synergizing Reasoning and Acting in Language Models. ICLR.','https://arxiv.org/abs/2210.03629'),
  ('Gao et al. (2023). Enabling Large Language Models to Generate Text with Citations. EMNLP.','https://arxiv.org/abs/2305.14627'),
  ('Moreau and Missier, eds. (2013). PROV-DM: The PROV Data Model. W3C Recommendation.','https://www.w3.org/TR/prov-dm/'),
  ('Gebru et al. (2021). Datasheets for Datasets. Communications of the ACM.','https://arxiv.org/abs/1803.09010'),
 ],
 'pages':[
 page('', h('Abstract'),
  p('A presentation transcript provides an incomplete entry point into its speaker, subject, setting and intellectual history. This proposal asks whether a bounded agent can gather a more useful, source-supported dossier than a fixed retrieval pipeline when both have identical access and resource budgets. The projected system will resolve candidate entities, maintain explicit information needs, select among approved resource adapters and revise its search in response to new evidence. Every output claim will retain a source version and locator. [1]'),
  p('The principal research contribution would be a controlled comparison of adaptive exploration against reproducible fixed retrieval, rather than an unrestricted demonstration of web browsing. A proposed transcript-level evaluation separates identity errors, evidence coverage, citation support, uncertainty and resource use. Public-source snapshots will support deterministic replay; a separate live condition will measure sensitivity to changing resources. Neither a longer dossier nor a greater number of tool calls will be treated as evidence of better research.'),
  h('Status and scope'),
  note('NOT STARTED. This is a projected solution and research plan. Implementation and empirical evaluation have not begun. The examples, sample sizes, budgets and acceptance thresholds are proposed; no experimental results are reported.'),
  p('The work is planned as an independent individual portfolio project by Boomer Rawlings, after the original submission and grading dates. It is not a SCADS group submission. The public product page will present this proposal and its roadmap until an implemented demonstration can be documented.'),
 ),
 page('1. Research question and related work',
  p('The problem book specifies an input transcript, information about speakers and topics, contextual details such as venue and period, and previous related talks. Retrieval must remain inside a predetermined source set. The proposed interpretation is evidence completeness within a declared collection and budget, rather than the impossible claim that all relevant information on the open web has been found. [1]'),
  h('Research questions'),
  p('RQ1: Does adaptive selection of retrieval actions improve supported coverage at matched cost? RQ2: Does explicit identity uncertainty reduce mistaken speaker merges? RQ3: Does a provenance ledger help a reader verify a dossier more accurately or quickly? RQ4: How much does performance change when a frozen resource snapshot is replaced by live adapters? These questions distinguish planning benefit, reliability, human utility and environmental instability.'),
  p('ReAct combines language-guided reasoning and external actions, motivating a controller that can revise its next action after observing evidence. This proposal adopts that interaction pattern but tests it under a fixed allowlist and a bounded action budget; it does not assume that agentic planning necessarily outperforms a fixed pipeline. [2]'),
  p('ALCE treats generation with citations as an evaluation problem involving answer quality and citation support. It motivates claim-level checking here, where merely attaching a URL is insufficient. PROV-DM supplies a vocabulary for entities, activities, attribution and derivation; it motivates a portable evidence record rather than an opaque browsing history. Dataset documentation follows the transparency goals of Datasheets for Datasets. [3] [4] [5]'),
  h('Falsifiable contribution'),
  p('The central hypothesis is a positive paired difference in supported coverage under the same budget without a material loss in claim precision. If a fixed pipeline performs equally well, the appropriate conclusion is that planning adds complexity without demonstrated benefit for this task distribution. A replayable dataset and diagnostic failure taxonomy would remain useful contributions.'),
 ),
 page('2. Proposed architecture and data contracts',
  p('The projected implementation has four boundaries: transcript admission, a policy-enforcing resource broker, an evidence ledger and a dossier generator. The controller can request actions but cannot add domains, override adapter permissions or convert retrieved instructions into executable directives. Source text remains untrusted input. Only broker-approved fetches can create evidence records.'),
  table(['Component','Proposed contract','Audit record'],[
   ['Transcript','Text, speaker hints, segment times, rights record','Input hash; supplied vs inferred fields'],
   ['Source adapter','Search, fetch, metadata, bounded media inspection','Allowlist version; query; response hash'],
   ['Claim ledger','Subject, predicate, value, date, modality, support','Source version; passage or frame locator'],
   ['Controller','Choose next information need and approved action','Action reason code; budget before/after'],
   ['Dossier','Claim-linked narrative plus unresolved alternatives','Citations; coverage; abstentions; trace'],
  ],[86,205,197]),
  p('Each source record will contain a stable ID, original URL, retrieval time, publication time when supplied, content hash, media type, rights note and adapter identity. Time fields will remain separate. A transcript reference to last year will be interpreted only if the talk date is sufficiently supported. Multiple mirrors of the same biography will belong to one origin cluster rather than count as independent corroboration.'),
  p('A candidate speaker will be represented as an unresolved set of identities until distinguishing evidence is available. A shared name and overlapping topic are weak evidence; an official event page linking a talk and an institutional biography is stronger. The model may suggest candidates, but only explicit source-supported links enter the ledger. Identity decisions retain alternatives and the evidence used to choose.'),
  note('Planned interface: transcript at left, information-needs board in the center, evidence and citations at right. A user can inspect source support and request a bounded follow-up without silently changing the approved collection.'),
 ),
 page('3. Projected retrieval and synthesis method',
  p('Initial transcript processing will identify candidate speakers, named topics, event hints and temporal expressions. It will also construct a question list: who is speaking, what concepts require clarification, what event is this, and which earlier talks are explicitly connected? These are hypotheses to investigate, not extracted facts. A deterministic first pass will establish a baseline that can be reused by every comparison condition.'),
  h('Bounded adaptive loop'),
  p('At step t, the controller observes an evidence summary E(t), unresolved needs U(t) and remaining budget B(t). It chooses an approved action a(t), the broker validates it, and the returned source is normalized into the ledger. The controller may expand, verify, backtrack or stop. The initial candidate policy will rank actions by expected reduction of important unresolved needs divided by estimated action cost; estimates are heuristic scores, not calibrated probabilities.'),
  p('The first implementation will use a transparent finite action menu and a maximum of 12 retrieval actions per transcript. This is a proposed experimental budget, not a measured optimum. A stop action is valid when core needs have support, the remaining sources are exhausted, or further retrieval would exceed the budget. Every stop preserves unresolved items. Backtracking changes the investigation path without deleting earlier evidence or treating rejected hypotheses as findings.'),
  h('Multimodal evidence'),
  p('When approved pages contain relevant images or video, the adapter will return a bounded frame/time locator and provenance. Captions, transcripts and image interpretation will remain separate evidence types. Only explicit visual claims will require visual inspection; unrelated media will not be collected merely because it is available. Authored regression fixtures will include absent attachments and mismatched captions.'),
  p('The generator will produce short atomic claims before prose. A verifier will check that each citation exists, was actually retrieved and supports the stated subject, relation and time. Contradictory claims remain visible. Unsupported claims are removed or expressed as unresolved questions, and a final narrative is assembled from the checked claim ledger.'),
 ),
 page('4. Experimental design and measurement',
  p('The proposed pilot contains 24 rights-qualified talks for debugging and annotation calibration. A subsequent target evaluation of 120 transcripts would be split by speaker and event series, keeping related talks in the same partition. Final size will be revised using pilot variance and annotation cost before test access. A topic-only split would allow near-duplicate speaker biographies to leak across partitions.'),
  table(['Condition','Purpose','Controlled factors'],[
   ['Transcript only','Value of external evidence','Same generation model and answer limit'],
   ['Fixed retrieval','Non-agentic reference','Same approved sources and fetch budget'],
   ['Adaptive retrieval','Planning effect','Same model, index and cached responses'],
   ['Adaptive, no verification','Verification ablation','Identical initial retrieved evidence'],
   ['Human reference subset','Verification utility','Counterbalanced order; timed tasks'],
  ],[130,154,204]),
  p('Two annotators will label transcript-specific information needs and source support; disagreement will be adjudicated before test scoring. The evaluation pool will combine outputs from all methods and independent expert searches inside the allowlist. A sampled audit of documents outside that pool will estimate pooling incompleteness. The resulting reference is bounded by the collection and annotation process, not exhaustive world knowledge.'),
  p('Claim precision equals supported emitted claims divided by all checkable emitted claims. Supported coverage is the weighted fraction of reference needs satisfied with adequate citations. Citation precision measures whether cited passages support their linked claims; citation completeness measures the fraction of checkable claims with sufficient support. Identity merge errors, contradiction preservation, abstention quality, tool calls, tokens and wall time will be reported separately.'),
  p('Each stochastic condition will use three prespecified seeds. Differences will be paired by transcript; confidence intervals will resample speaker/event clusters rather than individual claims. Human verification time will be analyzed alongside verification accuracy, so fast but incorrect judgments cannot be described as improved usability.'),
 ),
 page('5. Robustness, validity and decision rules',
  p('Prespecified perturbations will include ambiguous names, missing event dates, transcript recognition errors, stale biographies, repeated syndicated text, contradictory dates, tool outages and prompt-injection text in retrieved pages. These test mechanism-level behavior. Natural transcripts and authored perturbations will be reported as separate strata so a strong synthetic score does not hide weak performance on ordinary material.'),
  h('Decision rules'),
  p('A proposed research success rule is a positive lower bound on the paired supported-coverage difference against fixed retrieval, while the lower confidence bound for claim-precision difference remains above a preregistered noninferiority margin of -0.02. The margin represents a design tolerance to discuss before annotation; it is not evidence that a two-point loss is acceptable in every application. Budget compliance and zero unapproved fetches are deterministic gates.'),
  p('Coverage, precision and latency will also be plotted as a Pareto frontier across budgets of 4, 8 and 12 actions. This avoids declaring a method superior merely because it spends more. Every timeout, parser failure and empty response will count in the denominator for the relevant task-level measure. Successful cases alone will not define the evaluation cohort.'),
  h('Threats to validity'),
  p('Approved sources may overrepresent prominent English-speaking presenters. A dossier benchmark may reward readily discoverable biographies while neglecting topic synthesis. Automatic citation checkers can mistake topical overlap for entailment. The proposed mitigations are source-coverage reporting, a stratified transcript sample and manual auditing of high-confidence judgments. A separate human study would be needed before claiming reduced analyst burden.'),
  p('Public availability does not justify assembling unnecessary personal profiles. The planned dossier scope is professional context directly relevant to the talk. It excludes sensitive personal inference and unrelated contact details. Rights and retention decisions will be made per source; the release will prefer hashes, locators and admissible excerpts over redistributing complete third-party media.'),
 ),
 page('6. Implementation roadmap and reproduction plan',
  table(['Phase','Planned work','Exit evidence'],[
   ['A: specification','Freeze approved resources, claim schema, inclusion rules','Reviewed contracts and dataset sheet'],
   ['B: deterministic core','Build broker, snapshots, fixed retrieval and ledger','Replay equality; allowlist denial tests'],
   ['C: agent loop','Add planning, verification, budgets and abstention','Authored cases pass without live services'],
   ['D: pilot','Annotate24 talks; estimate cost and variance','Adjudication guide; frozen scoring protocol'],
   ['E: evaluation','Freeze methods; run held-out transcript clusters','Complete traces; paired confidence intervals'],
   ['F: release','Publish accessible viewer, paper and reproduction kit','Independent clean-environment replay'],
  ],[95,205,188]),
  p('The roadmap is ordered by dependencies, not a promise of calendar dates. Source licenses and annotator availability are feasibility gates. If the approved collection cannot support the required information needs, the protocol will narrow its population explicitly rather than silently supplementing it with unrestricted search.'),
  p('The planned run manifest will pin the input transcript, allowlist, adapter versions, model/revision, prompt templates, seed, tool budget, source hashes and scoring configuration. A replay mode will read frozen adapter responses; a live mode will write a separate record. Their results will never be pooled without an explicit environmental-change analysis.'),
  p('A future demonstration will use an authored talk fixture to let visitors expand an information need, inspect candidate identities and follow a dossier citation. Until implementation begins, the product page will offer the projected workflow and this research plan. The present repository directory contains documentation only; there is no runnable agent or evaluation dataset.'),
  note('Expected contribution: evidence about when bounded adaptive retrieval helps, together with a reproducible provenance workflow. A null result remains publishable if the comparison is controlled and failures are reported.'),
 ),
 page('7. References and publication record',
  p('Primary sources consulted October 7, 2026. They motivate the research design; they do not validate the projected implementation. Source [1] is the user-supplied problem book, and the requirement summary is paraphrased. No source document is redistributed in this proposal.'),
  ('refs',),
  h('Planned release materials'),
  p('The intended future release comprises source adapters, a documented claim schema, authored regression fixtures, hash-pinned public snapshots where rights permit, annotation instructions, a frozen run manifest and an evidence viewer. Data-access restrictions will be recorded alongside reproduction instructions. Documentation will identify all transformations from transcript to claim and all human adjudication steps.'),
  h('Current publication record'),
  p('This document is an independently authored research proposal. All architectural choices, sample counts, action budgets and acceptance rules are projected choices subject to preregistration. No software execution, model accuracy, analyst-time improvement or retrieval advantage is claimed. Status: Not started.'),
 )]
},
{
 'number':'07', 'slug':'07-efficient-agentic-rag', 'short':'EFFICIENT AGENTIC RAG',
 'title':'Retrieval only when it earns its cost',
 'subtitle':'A projected study of adaptive multilingual RAG and evidence-aware evaluation',
 'refs':[
  ('SCADS 2026 Problem Book, Project 7, p. 9. User-supplied research brief.', None),
  ('Jeong et al. (2024). Adaptive-RAG: Learning to Adapt Retrieval-Augmented Large Language Models through Question Complexity. NAACL.','https://arxiv.org/abs/2403.14403'),
  ('TREC RAG organizers (2024). TREC 2024 RAG Track Guidelines.','https://trec-rag.github.io/annoucements/2024-track-guidelines/'),
  ('TREC RAGTIME organizers (2026). Official track description and language scope.','https://trec-ragtime.github.io/'),
  ('NIST (2026). TREC call for participation, AutoJudge track description.','https://trec.nist.gov/cfp.html'),
  ('Zheng et al. (2023). Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena. NeurIPS.','https://arxiv.org/abs/2306.05685'),
 ],
 'pages':[
 page('', h('Abstract'),
  p('Retrieval-augmented generation must balance evidence quality against retrieval, reasoning and translation cost. This proposal studies a compact controller that chooses among no retrieval, single-pass retrieval and bounded iterative retrieval, with multilingual query expansion when the available evidence warrants it. The projected evaluation separates the contribution of adaptive retrieval from the contribution of an improved automatic judge. Both are measured against frozen, non-adaptive baselines. [1]'),
  p('The English evaluation will use a pinned TREC 2024 RAG release. A separately pinned RAGTIME edition will supply multilingual report and retrieval tasks. The proposed judge will score support, completeness and cross-language consistency against source passages and human annotations. Held-out agreement, language-specific error and ranking stability will determine whether its output is usable as an evaluation instrument, rather than assuming that a fluent explanation establishes a reliable judgment. [3] [4]'),
  h('Status and scope'),
  note('NOT STARTED. Projected solution and research plan only. Implementation, dataset preparation and experimental evaluation have not begun. All proposed targets and budgets are design parameters; no measured results are reported.'),
  p('Planned as independent individual work by Boomer Rawlings after the original submission and grading dates. The initial contribution would be a reproducible quality-cost comparison and a calibrated judge protocol. The scope is research evaluation, not a claim that one retrieval policy or language model is universally best.'),
 ),
 page('1. Motivation, literature and hypotheses',
  p('An easy query may be answered with a single relevant passage, while a report request may require several facets and sources. Applying the same retrieval depth to both can waste resources or omit evidence. Cross-language retrieval adds another decision: whether to search shared embeddings directly, translate the query, or combine both. The proposed controller will make these choices under an explicit budget, preserving their costs in the run record.'),
  p('Adaptive-RAG motivates routing queries to retrieval strategies with different complexity. This proposal will reproduce the routing idea as a baseline and test a controller that also observes retrieved evidence gaps. The intended novelty is a controlled interaction between adaptive budgets, cross-language retrieval and judge reliability; the project does not claim to invent adaptive retrieval. [2]'),
  p('TREC 2024 RAG defines retrieval, augmented generation and end-to-end RAG tasks with cited answers and evaluation of retrieval, nuggets, support and fluency. RAGTIME emphasizes multifaceted multilingual reports and cited evidence; its current official scope includes English, Spanish, Chinese and Russian. The exact benchmark edition and available judgments will be frozen before experimentation. [3] [4]'),
  p('AutoJudge is a NIST meta-track for automatic judgments over runs from other tracks. It will inform the evaluation protocol when suitable challenge data is available. LLM-as-a-judge research documents position, verbosity and self-preference biases, which motivate blinded scoring and perturbation tests here. No published agreement level is assumed to transfer to this multilingual setting. [5] [6]'),
  h('Falsifiable hypotheses'),
  p('H1: adaptive retrieval reduces median end-to-end cost at noninferior grounded completeness. H2: language-aware expansion improves multilingual evidence coverage at equal document budget. H3: evidence-conditioned judges outperform answer-only judges on held-out human support labels. Each hypothesis will be tested separately, with interaction effects reported rather than hidden in one aggregate score.'),
 ),
 page('2. Proposed system and budget model',
  table(['Stage','Projected behavior','Recorded cost'],[
   ['Query analysis','Identify language, facets and answer constraints','Classifier tokens and latency'],
   ['Route','Choose none, single-pass or iterative retrieval','Policy version and chosen budget'],
   ['Retrieve','Lexical, multilingual dense or fused search','Queries, candidate counts, index time'],
   ['Expand','Translate or reformulate unresolved facets','Translation tokens and calls'],
   ['Generate','Compose claim-linked answer from evidence','Input/output tokens and wall time'],
   ['Evaluate','Score support, completeness and uncertainty','Judge calls, human audit time'],
  ],[83,248,157]),
  p('The initial controller will be a small supervised classifier with a transparent fallback policy. Its inputs will be query features and retrieval diagnostics available at decision time, including language, requested facets, score dispersion and evidence overlap. Gold relevance judgments and final answer scores will never be available to the test-time controller. Training labels will be generated only from development runs.'),
  p('A budget vector B = (retrieval calls, retrieved tokens, generation tokens, elapsed time) will be enforced by the orchestration layer. Monetary cost, when applicable, will be derived from separately recorded dated prices; it will not substitute for token and time measurements. Local models will report hardware, power mode and concurrency. Translation, reranking, routing and failed calls are part of total cost.'),
  p('The first study will compare at most three retrieval iterations and matched final context limits. These are projected bounds chosen for interpretable experiments. A controller that exhausts its budget must return a partial supported answer or abstention. It cannot silently increase the context window, call an uncounted search service, or reuse test judgments as a confidence signal.'),
  note('Projected data path: query -> route -> retrieve/expand -> evidence ledger -> cited answer. Evaluation consumes the frozen ledger and answer; it cannot alter the submitted response.'),
 ),
 page('3. Multilingual retrieval and answer attribution',
  p('Four baseline retrieval conditions are proposed: lexical search in the query language, multilingual dense search, translate-then-lexical search, and reciprocal-rank fusion of lexical and dense candidates. Index construction, chunk boundaries and final evidence budgets will be identical where meaningful. Model revisions and tokenizer differences will be recorded so a better encoder is not misattributed to the controller.'),
  h('Separate languages and task directions'),
  p('RAGTIME report generation into English from multilingual evidence is distinct from answering arbitrary questions in each source language. The primary evaluation will follow the selected track edition exactly. Any additional translated-query experiment will form a separate dataset with its own annotation and translation provenance. Scores from different task directions will not be pooled under a generic multilingual label.'),
  p('Every translated query will retain its original text, target language, translation model and revision. Named entities, dates, quantities, negation and uncertainty markers will be checked explicitly. A translated passage is a derived artifact; its citation points to the original source and an aligned passage locator, while the translation is retained for inspection. Back-translation is a diagnostic, not proof of semantic equivalence.'),
  h('Evidence-aware stopping'),
  p('The controller will maintain unresolved report facets and the sources supporting each candidate claim. It may stop when requested facets have adequate evidence, when no new sources appear, or when the budget is exhausted. A learned stopping model will be compared with a fixed iteration count and a simple novelty rule. An ablation will remove language labels to test whether language-aware routing provides benefit beyond generic uncertainty.'),
  p('Cross-language agreement between two passages will not automatically count as independent corroboration: translated mirrors and syndicated copies will be clustered by origin where metadata permits. Contradictions will retain source language and time. Evaluation will distinguish missed evidence, translation distortion and generation error so a final wrong answer can be attributed to a specific stage.'),
 ),
 page('4. Projected judge and human reference protocol',
  p('The planned judge input contains the request, answer, cited passages, source languages and a rubric. It produces structured judgments for atomic claim support, missing required facets, contradiction and cross-language semantic fidelity. Each decision must name the relevant passage span or state insufficient evidence. A score without such a locator is treated as an invalid evaluation output.'),
  table(['Dimension','Reference question','Primary check'],[
   ['Support','Does the cited source entail this claim?','Human claim-passage label'],
   ['Completeness','Which required information nuggets are covered?','Frozen nugget inventory'],
   ['Cross-language fidelity','Are entities, quantities and modality preserved?','Bilingual adjudication'],
   ['Contradiction','Does the answer hide conflicting source claims?','Conflict-bearing task slice'],
   ['Usability','Is the report coherent and task-responsive?','Separate ordinal human rubric'],
  ],[112,219,157]),
  p('The proposed pilot will double-annotate at least 200 claim-passage pairs, stratified by source language and support class. The final annotation target will be set from pilot disagreement and confidence-interval width before held-out evaluation. Annotators will see blinded system identities. Disagreements will be adjudicated, while initial labels remain available for estimating reliability. Language proficiency and adjudication instructions will be documented.'),
  p('Judge calibration will use development labels only. A held-out set will report macro-F1, class-specific recall, confusion matrices, abstention coverage and calibration error where the judge emits probabilities. System-level ranking agreement will be reported alongside item-level agreement, since high overall agreement can still reverse the ordering of close systems.'),
  p('Bias checks will swap answer order, remove system names, equalize formatting and compare concise versus verbose paraphrases. A model-family holdout will test judge transfer to outputs from unseen generators. No system will receive sole credit from a judge drawn only from its own model family.'),
 ),
 page('5. Evaluation design and statistical analysis',
  p('The proposed study has two stages. First, reproduce fixed retrieval/generation baselines on a pinned English release and the selected multilingual edition. Second, compare adaptive policies at matched evidence budgets and several prespecified cost ceilings. Training, tuning, judge calibration and final evaluation partitions will be separated by topic family; paraphrases and translated variants stay together.'),
  p('Primary retrieval metrics will be nDCG and recall at declared cutoffs using the selected release judgments. Generation will use supported nugget coverage, claim-level support and contradiction rates. Unjudged documents will be handled according to the benchmark protocol and sensitivity analyses, not silently treated as irrelevant. Human-grounded metrics will remain distinct from judge-derived estimates.'),
  p('Quality-cost comparisons will show paired per-topic differences, Pareto frontiers, median latency and tail latency. Topic-cluster bootstrap intervals will account for shared translations and repeated seeds. A prospective noninferiority margin of two percentage points in supported coverage is proposed for discussion; it must be fixed before evaluation. An adaptive system earns an efficiency claim only when its quality condition and cost reduction both pass.'),
  h('Ablations and failure accounting'),
  p('Ablations will remove adaptive stopping, query translation, multilingual fusion and evidence-conditioned judging one component at a time. A factorial subset will test whether translation helps only with particular retrieval policies. All failed runs, budget exhaustion and unavailable documents remain in the task denominator. Cost comparisons will distinguish cold and warm caches, index preparation and online answering.'),
  p('A negative outcome is informative: the controller may save tokens only by omitting relevant facets, or the judge may agree on easy English cases while failing cross-language negation. Such findings would narrow the deployment recommendation. No single blended score will be used to conceal a quality-cost tradeoff or a low-performing language stratum.'),
 ),
 page('6. Roadmap, reproducibility and validity',
  table(['Phase','Planned deliverable','Exit criterion'],[
   ['A: benchmark freeze','Edition, licenses, split and scoring manifest','Data access and evaluation scope verified'],
   ['B: fixed baselines','Lexical/dense/fused retrieval plus cited generation','Reproducible runs and cost accounting'],
   ['C: controller','Routing, translation, stopping and budget enforcement','No hidden test labels; bounded actions'],
   ['D: judge pilot','Bilingual rubric and adjudicated development labels','Bias checks; sample-size decision'],
   ['E: frozen comparison','Held-out runs and paired analyses','All runs included; confidence intervals'],
   ['F: publication','Paper, manifests, scripts and demonstration','Independent reproduction of scoring'],
  ],[93,210,185]),
  p('The run manifest will pin collection version, document IDs, chunking, indexes, model revisions, prompts, seeds, language routes, budgets, hardware and cache state. A separate judge manifest will identify rubric, model, calibration split and parser version. Generated evaluation artifacts will never overwrite the original answer or source evidence.'),
  p('Dataset availability, reuse terms and human judgment coverage are feasibility gates. A newer track release is not interchangeable with the 2024 English benchmark. Likewise, translation quality and document-topic imbalance may dominate nominal language effects. The analysis will report per-language sample sizes and uncertainty, and will avoid claiming typological generality from four languages.'),
  p('A future product demonstration will display the retrieval route, remaining budget and source-linked answer for an authored multilingual fixture. The current publication offers this plan only. There is no working controller, judge implementation or measured quality-cost frontier in this project directory.'),
 ),
 page('7. References and proposed contribution',
  p('Primary sources consulted October 7, 2026. Track descriptions are version-sensitive; the experiment must preserve the edition actually used. The following references establish context and evaluation resources, not results for this projected system.'),
  ('refs',),
  h('Expected research artifact'),
  p('The intended contribution is a transparent answer to two questions: when does adaptive multilingual retrieval pay for its extra decisions, and when can an automatic judge reliably detect the resulting quality changes? The planned evidence package will retain the underlying answers, citations and human labels so readers can recompute conclusions under alternative metric choices.'),
  note('Current status: Not started. All methods, budgets, annotation targets and comparisons in this paper are projected. No performance ranking, measured speedup or empirical judge reliability is claimed.'),
 )]
}]

PROPOSALS.extend([{
 'number':'08', 'slug':'08-capability-benchmarks', 'short':'CAPABILITY BENCHMARKS',
 'title':'Measure the task, not the reputation',
 'subtitle':'A projected benchmark suite for use-case-specific AI capabilities',
 'refs':[
  ('SCADS 2026 Problem Book, Project 8, pp. 10-11. User-supplied research brief.', None),
  ('Liang et al. (2023). Holistic Evaluation of Language Models. TMLR.','https://arxiv.org/abs/2211.09110'),
  ('Jimenez et al. (2024). SWE-bench: Can Language Models Resolve Real-World GitHub Issues? ICLR.','https://arxiv.org/abs/2310.06770'),
  ('Gebru et al. (2021). Datasheets for Datasets. Communications of the ACM.','https://arxiv.org/abs/1803.09010'),
  ('Zheng et al. (2023). Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena. NeurIPS.','https://arxiv.org/abs/2306.05685'),
 ],
 'pages':[
 page('', h('Abstract'),
  p('A model benchmark supports a deployment decision only when its tasks, allowed tools and scoring rules resemble the intended use. This proposal develops a modular assessment suite for scientific assistance, software maintenance, defensive code analysis, multilingual understanding and appropriate refusal. The projected system will define each capability as an observable task contract with independent evidence of success. It will publish capability profiles and cost distributions rather than collapse every dimension into a single ranking. [1]'),
  p('The primary research question is whether domain-specific tasks reveal capability differences and failure modes that broad public scores obscure. A second question asks how benchmark validity changes when an agent helps generate its own tasks. The proposed design separates task authorship, solution generation and adjudication; retains hidden family-level holdouts; and tests whether conclusions remain stable under alternate rubrics, tool budgets and model revisions. No task generation or evaluation has yet occurred.'),
  h('Status and scope'),
  note('NOT STARTED. This paper is a projected solution, study design and implementation roadmap. No benchmark suite, model run, scored dataset or capability result is claimed. Sample counts and decision margins are proposed planning values.'),
  p('This is planned independent individual work by Boomer Rawlings after the original submission and grading dates. The government-relevant framing motivates the task categories; all proposed examples use public, licensed or authored material. The project does not claim operational certification or access to government data.'),
 ),
 page('1. Construct validity and related work',
  p('A useful assessment starts with the decision it must inform. Can an assistant find a statistical error without inventing missing data? Can a coding agent repair a compiler-sensitive numerical routine while preserving behavior? Can a language model retain implication and uncertainty across languages? These are different constructs. They require different reference evidence and cannot be represented faithfully by one generic accuracy score.'),
  p('HELM motivates evaluation across multiple scenarios and metrics under standardized conditions. This proposal adopts that emphasis on transparent profiles, but narrows each task to a concrete workflow and decision. SWE-bench motivates repository-level issue resolution with executable checks; its original Python-focused design is a methodological reference, not evidence that the same tasks measure competence in legacy languages. [2] [3]'),
  p('Datasheets for Datasets motivates documenting collection, composition and intended use. Here that documentation will include construct definitions, task-family provenance, author access to model outputs and the conditions under which a score should not guide deployment. LLM-as-a-judge research motivates blinded comparisons and bias checks, while the proposed suite will prefer executable or independently adjudicated evidence wherever possible. [4] [5]'),
  h('Research questions'),
  p('RQ1: Are model capability profiles stable across task families within a use case? RQ2: Which tool and cost constraints change the model ordering? RQ3: Do domain-specific failures add information beyond broad public benchmark scores? RQ4: Does self-generated evaluation overestimate capability compared with independently authored holdouts? These questions require task-level results and uncertainty, not anecdotal demonstrations.'),
  p('The initial implementation will focus on two vertical slices, scientific reasoning and software maintenance, before adding the remaining tracks. This is a feasibility choice: validity in a small, well-annotated suite is more useful than superficial coverage. The full roadmap retains all task families from the brief, with separate admission criteria and reviewers.'),
 ),
 page('2. Proposed task taxonomy and contracts',
  table(['Track','Projected task','Independent success evidence'],[
   ['Scientific assistant','Analyze a supplied dataset and defend a conclusion','Executable analysis; hidden data checks; expert rubric'],
   ['Software maintenance','Repair an authored Fortran/Ada or Python defect','Compiler matrix; hidden regression tests; review'],
   ['Defensive analysis','Inspect an owned toy binary or source package','Known seeded weakness; bounded artifact rubric'],
   ['Language understanding','Interpret culturally grounded, contextual passages','Bilingual rationale and adjudicated semantic labels'],
   ['Appropriate refusal','Respond to matched permitted/restricted task pairs','Policy-grounded labels; helpfulness and boundary scores'],
  ],[96,198,194]),
  p('Each task contract will declare the user goal, input artifacts, tool permissions, time and token budget, output format, scoring components and disqualifying behavior. An immutable task ID will identify the exact contract version. The harness will retain the final artifact, relevant tool actions, errors and resource accounting. Private reasoning text will not be required as a scoring input; observable decisions and artifacts are sufficient.'),
  p('A scientific task may contain a planted confound, unit mismatch or unsupported causal conclusion. The score will distinguish correct computation from warranted interpretation. A coding task will require a minimal repair that passes hidden tests and preserves an interface, rather than reward matching a reference patch. Defensive analysis will remain inside isolated, owned examples; it will not involve probing real targets or publishing operational exploit instructions.'),
  p('Language tasks will include ambiguity, implicature, register and context, with annotators documenting acceptable interpretations. Refusal tasks will include benign analysis of sensitive-looking text as well as requests that require boundaries. The goal is to measure both over-refusal and unsafe compliance using authorized, non-operational fixtures, not to optimize methods for bypassing safeguards.'),
 ),
 page('3. Dataset construction and contamination control',
  p('The proposed authoring process begins with a construct map and task-family templates reviewed by domain specialists. Authors will create a task, reference evidence and rubric before inspecting evaluated model outputs. Every artifact will receive a rights record and a provenance entry describing whether it was human-authored, model-assisted, adapted from a public source or generated by a deterministic script.'),
  h('Separate design, development and test'),
  p('A pilot target of 20 tasks in each of the first two tracks will calibrate instructions and scoring. A later target of 100 tasks per admitted track will be revised using pilot variance, task-family diversity and reviewer cost. Families, repositories and source documents will be assigned wholly to one partition. Superficial paraphrases of the same problem will not be treated as independent examples.'),
  p('Public tasks will support reproducibility; a separately governed rotating holdout will test generalization to unseen task families. Publication dates, source commits and known benchmark overlap will be recorded. Similarity scanning can identify obvious duplicates but cannot prove absence from unknown training corpora. Results will therefore distinguish contamination controls from claims of contamination-free evaluation.'),
  h('Self-evaluation experiment'),
  p('To study recursive self-evaluation, one arm will let an agent propose task instances from a declared domain. Those tasks must pass independent validity review before scoring. The generating model, sibling model families and independent models will then be evaluated on both generated tasks and independently authored holdouts. The main comparison is the change in the generator advantage across those two sets.'),
  p('Generated tasks that are invalid, ambiguous or unsolvable will be counted and characterized, not quietly removed from the generation yield. Scoring the same model against its own unreviewed answers would be circular; independent adjudication and holdouts are essential. A high self-generated score can indicate alignment with the generator distribution rather than broad competence.'),
 ),
 page('4. Harness and scoring methodology',
  p('The planned harness will execute versioned tasks in isolated workspaces with bounded tools and deterministic artifact collection. A model adapter will normalize requests and return output plus usage metadata. The evaluator will operate in a separate process with hidden checks unavailable to the agent. Network access, package installation and filesystem scope will be specified per task and logged when allowed.'),
  table(['Scoring layer','What it measures','Proposed protection'],[
   ['Executable checks','Functional correctness and invariants','Hidden tests; independent fixtures; tamper checks'],
   ['Artifact rubric','Completeness, support and interpretation','Blinded dual review; adjudication'],
   ['Behavior trace','Authorized actions, recovery and uncertainty','Observable action labels; no reasoning-text demands'],
   ['Resource record','Time, tokens, tool calls and memory','Count retries, failures and setup separately'],
   ['Judge assistance','Suggested rubric labels at scale','Human calibration; bias and transfer checks'],
  ],[114,184,190]),
  p('For coding tasks, a pass requires both issue-specific checks and regression preservation. A test harness that the agent can modify is not trusted as the sole oracle. Scientific tasks will preserve input data hashes and validate calculations independently. Narrative scoring will distinguish factual correctness, attribution and uncertainty; stylistic fluency will not compensate for incorrect claims.'),
  p('A partially completed artifact may receive component scores, but task success will use prespecified criteria. The suite will report pass@1 under one fixed budget as its primary operational measure. Additional attempts will be labeled separately with total cost; best-of-many results will not be described as single-attempt reliability.'),
  p('Automatic judges will receive blinded outputs and rubrics with order randomization. A held-out audit will compare their labels with independent reviewers. If judge agreement is inadequate in a task family, that family will use human scores or remain outside automatic aggregation. Judge confidence will never replace evidence that the rubric was applied correctly.'),
 ),
 page('5. Experimental analysis and decision utility',
  p('Models will be compared under the same task budgets, tool permissions and artifact constraints. The initial proposed panel includes at least three distinct model families and a deterministic or specialist baseline where meaningful. Versions and access dates will be pinned. A provider update creates a new condition; it does not silently replace an earlier measurement.'),
  p('Primary results will be per-track success, critical error rate, justified abstention and cost per successful task. Cost per success will include failed attempts in its numerator. Latency distributions and tail failures will accompany medians. A deployment-oriented view may apply stakeholder-defined minimum quality and maximum cost gates, but the underlying raw profile will remain available.'),
  h('Uncertainty and comparisons'),
  p('The task family is the principal resampling unit. Cluster bootstrap intervals will preserve related variants and repeated seeds. Pairwise differences will be computed on shared tasks, with a prespecified primary comparison and correction or explicit exploratory labeling for additional comparisons. A leaderboard difference smaller than its uncertainty will be reported as unresolved.'),
  p('The proposed analysis will test sensitivity to rubric weights, exclusion rules and tool budgets. Rankings that reverse under reasonable weight changes should guide a task-specific selection discussion rather than support a universal best-model claim. For scientific tasks, expert ratings will be analyzed alongside executable correctness; disagreement between them may reveal invalid shortcuts or overly restrictive references.'),
  h('Decision rules'),
  p('Before final runs, each use case will define unacceptable failure classes and a minimum evidence threshold. No single sample count is sufficient for rare critical failures: observing zero events in a small suite does not establish negligible risk. The report will state the finite-sample uncertainty and the population represented by each task family. Claims of government readiness or general intelligence are outside this study.'),
 ),
 page('6. Roadmap and validity safeguards',
  table(['Phase','Planned work','Exit evidence'],[
   ['A: construct map','Select decisions, task families and admissible tools','Expert-reviewed construct and scoring map'],
   ['B: vertical pilot','Author scientific and maintenance tasks','Solvability checks; dual-review agreement'],
   ['C: harness','Implement isolation, model adapters and hidden scoring','Replayable tasks; tamper and failure tests'],
   ['D: expanded suite','Admit defensive, language and refusal tracks','Qualified reviewers; rights/provenance records'],
   ['E: frozen study','Run comparisons and self-evaluation experiment','Complete cost/trace records; held-out analysis'],
   ['F: release cycle','Publish public suite and maintain rotating holdout','Versioned release and change-impact report'],
  ],[97,202,189]),
  p('Tasks will be retired or revised when they leak, become ambiguous after tool changes or stop representing the target workflow. A revision creates a new task version and a bridge evaluation on unaffected tasks. Benchmark maintenance is part of the design: a changing model landscape makes an unversioned aggregate score difficult to interpret.'),
  p('Reviewer expertise and disagreement are central validity risks. The protocol will document domain experience, language proficiency, adjudication and compensation where applicable. Task authors will not be the sole judges of outputs that challenge their expected solution. Independent alternate valid solutions will be admitted by a documented appeal process.'),
  p('A future product page could display a task contract, anonymized candidate artifacts and an inspectable scoring breakdown. The present page provides the proposal and roadmap only. No capability dashboard or working evaluation harness exists in this project yet. The next concrete step is to select the two pilot use cases and write reviewed task contracts.'),
 ),
 page('7. References and planned research contribution',
  p('Primary sources consulted October 7, 2026. These works motivate evaluation design and validity controls. They do not establish the performance of any model on this proposed suite.'),
  ('refs',),
  h('Planned publication package'),
  p('The intended release will contain task contracts, public inputs with rights records, reproducible environments, reference-check specifications, reviewer rubrics, anonymized adjudication labels where permitted, model-run manifests and scripts for uncertainty analysis. Hidden evaluation data will be governed separately, with documented access and a public description of its coverage.'),
  p('A useful outcome may be a narrow capability boundary rather than a winning model. Examples include a system that computes accurately but overstates causality, repairs common syntax while failing numerical invariants, or translates literal content while missing contextual implication. The proposed suite is designed to make such distinctions inspectable.'),
  note('Current status: Not started. The benchmark design is projected; implementation and evaluation have not begun. No empirical score, comparative ranking or operational adoption recommendation is reported.'),
 )]
},
{
 'number':'09', 'slug':'09-core-to-edge', 'short':'CORE-TO-EDGE VALIDATION',
 'title':'A model is not ready until the device is',
 'subtitle':'A projected validation and monitoring pipeline for resource-constrained deployment',
 'refs':[
  ('SCADS 2026 Problem Book, Project 9, p. 12. User-supplied research brief.', None),
  ('Banbury et al. (2021). MLPerf Tiny Benchmark. NeurIPS Datasets and Benchmarks.','https://arxiv.org/abs/2106.07597'),
  ('Xiao et al. (2023). SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models. ICML.','https://arxiv.org/abs/2211.10438'),
  ('Hinton, Vinyals and Dean (2015). Distilling the Knowledge in a Neural Network.','https://arxiv.org/abs/1503.02531'),
  ('Gebru et al. (2021). Datasheets for Datasets. Communications of the ACM.','https://arxiv.org/abs/1803.09010'),
 ],
 'pages':[
 page('', h('Abstract'),
  p('A model that meets quality targets in a development environment can fail after quantization, runtime conversion or deployment to a constrained device. This proposal specifies a core-to-edge validation pipeline that treats the deployable artifact, runtime and hardware profile as a single versioned unit. It will compare optimized models with a frozen reference, evaluate quality and resource gates, and monitor deployed behavior within a bounded overhead budget. [1]'),
  p('The projected study asks which core measurements predict device-level failures, how much calibration and validation data is necessary, and whether lightweight telemetry detects actionable degradation without erasing the resource savings of optimization. Physical-device trials will remain distinct from simulation. The planned output is an auditable release decision with reproducible measurements and rollback evidence, rather than a claim that compression alone makes a model edge-ready.'),
  h('Status and scope'),
  note('NOT STARTED. This is a projected solution, validation protocol and implementation roadmap. No model has been optimized, no hardware experiment has been run and no monitoring system has been deployed. All numerical budgets and thresholds are proposed study parameters.'),
  p('The project is planned as independent individual work by Boomer Rawlings after the original submission and grading dates. The initial scope is one modest classification workload and one compact language workload on explicitly identified device classes. Broader edge generalization would require additional tasks, devices and environmental conditions.'),
 ),
 page('1. Research questions and methodological context',
  p('The transition to edge deployment changes more than model weights. Kernel availability, operator fusion, memory allocation, precision, thermal limits, storage and input preprocessing can alter both correctness and resource use. The proposed unit of analysis is therefore a release tuple: model hash, tokenizer/preprocessor hash, runtime build, configuration and device profile. Comparing only model names would confound these factors.'),
  p('MLPerf Tiny motivates measuring accuracy, latency and energy together for resource-constrained inference. Its tasks and measurement discipline are useful references, while its results cannot be transferred directly to a compact language workload or a different device. SmoothQuant motivates one post-training quantization candidate for suitable language models; the availability of a method does not guarantee that a selected runtime has efficient kernels for it. [2] [3]'),
  p('Knowledge distillation motivates a student model trained to preserve useful behavior of a larger teacher. It will be treated as a separate optimization family with its own training-data and compute costs. Dataset documentation will record calibration, training and evaluation partitions, preventing a small calibration set from being mistaken for independent validation. [4] [5]'),
  h('Research questions'),
  p('RQ1: Which core measurements predict quality or resource gate failures on physical devices? RQ2: How do quantization, distillation and runtime conversion affect different task slices? RQ3: How does calibration-set size and diversity change quality retention? RQ4: What monitoring signal provides useful detection under a fixed compute, memory and telemetry budget?'),
  p('The principal hypothesis is that a release gate combining slice-level quality, tail latency, memory headroom and artifact checks predicts successful device execution better than mean accuracy alone. This is a projected hypothesis. A second hypothesis is that stratified calibration data reaches a given quality target with fewer samples than an unstratified subset; neither outcome is assumed.'),
 ),
 page('2. Proposed release architecture and contracts',
  table(['Tier','Planned responsibility','Retained evidence'],[
   ['Core training','Train or select reference; optimize candidates','Data splits; weights; optimizer configuration'],
   ['Core validation','Quality tests, conversion checks and stress profiles','Paired outputs; failure slices; gate decisions'],
   ['Device qualification','Physical execution under declared conditions','Latency/energy traces; runtime and device IDs'],
   ['Edge inference','Run approved artifact; enforce local budgets','Bounded summaries; local error counters'],
   ['Core operations','Aggregate telemetry; review drift; authorize updates','Version lineage; rollout and rollback records'],
  ],[105,207,176]),
  p('The release manifest will identify model and auxiliary file hashes, compatible operator/runtime versions, input schema, expected output schema, supported hardware and measured gates. A device will reject an incompatible or incomplete bundle before activation. Integrity verification and an atomic activation record will distinguish downloading a candidate from making it the active model.'),
  p('The initial projected design uses a signed manifest, a staged candidate slot and a known-good rollback slot. An interrupted download can resume without activating partial files. Activation occurs only after local integrity and smoke checks. The rollback decision preserves the prior working artifact and the failed candidate evidence. These are proposed mechanisms requiring implementation and fault-injection verification.'),
  p('Training, label adjudication and full evaluation remain at the core. The edge performs inference, budget enforcement and bounded monitoring. Telemetry is queued locally during disconnection with a fixed retention cap; aggregation records missing intervals rather than infer that silence means healthy operation. The proposed policy favors summary metrics and sampled diagnostics over uploading unrestricted raw inputs.'),
  note('The deployable artifact is the entire release tuple. A weight file passing a core test is necessary evidence, but it is not a device qualification result.'),
 ),
 page('3. Optimization study and data requirements',
  p('The initial experiment will compare a frozen reference with several admissible candidates: lower-precision conversion, post-training quantization, a distilled student and combinations supported by the runtime. Each candidate must preserve the input and output contracts or document the changed task. A conversion that changes preprocessing will be evaluated as a distinct system, not a pure precision change.'),
  h('Separate data roles'),
  p('Data will be partitioned into training, optimization/calibration, development validation and a locked final test set. For the language workload, prompts and documents from the same task family will stay together. For classification, repeated measurements from the same subject or device will remain in one partition where applicable. Calibration subsets will never be sampled from final test data.'),
  p('A proposed calibration-size sweep uses 32, 128, 512 and 2,048 examples when the dataset supports those counts, with three fixed subset seeds. Counts are planning parameters, not asserted minima. Random and stratified selection will be compared at equal size. Stratification will cover task labels, input length or complexity and stress slices without using final outcomes to choose the subset.'),
  p('Quality retention will be measured against both reference predictions and independent task labels. Agreement with an incorrect reference is not task accuracy. Language evaluation will include exact or executable checks where suitable and separately audited support/faithfulness labels for generated text. Distillation cost includes teacher inference and student training, while quantization cost includes calibration and conversion.'),
  h('Selecting a minimum'),
  p('The minimum-data estimate will be the smallest prespecified calibration condition whose confidence interval satisfies the quality gate on an independent validation set, followed by one locked-test confirmation. If intervals overlap the threshold, the answer is insufficient evidence, not an interpolated exact minimum. Curves and uncertainty will be reported by task slice; one global count cannot guarantee coverage of rare failures.'),
 ),
 page('4. Physical-device evaluation and release gates',
  p('Core resource limits and emulation will screen candidates, but final qualification requires actual target hardware. The proposed initial hardware matrix includes a CPU-only laptop-class device and a low-power ARM device, selected before measurement. Hardware model, RAM, operating system, runtime, power mode, ambient conditions and thermal state will be recorded. Simulator and device results will be presented separately.'),
  table(['Gate','Proposed measurement','Release interpretation'],[
   ['Task quality','Paired accuracy/support change and slice failures','Noninferiority margin fixed before testing'],
   ['Latency','Cold start, warm median and p95/p99','Meets declared interactive or batch budget'],
   ['Memory','Peak resident/device memory; allocator failures','Headroom remains under worst tested input'],
   ['Energy','External meter or qualified device counter','Report baseline subtraction and uncertainty'],
   ['Reliability','Repeated runs, restart, offline and update faults','No silent corruption; verified recovery'],
  ],[86,234,168]),
  p('An example planning gate is no more than a two-percentage-point task-quality loss with at least 15% memory headroom. These values are not universal acceptance standards; the actual task owner must choose them before evaluation. Latency and energy limits require a concrete device and use case. Passing a mean latency target while repeatedly missing the tail budget will count as failure.'),
  p('Trials will distinguish cold initialization, warmed steady state and sustained operation under thermal stress. Candidate order will be randomized or counterbalanced across repeated sessions. Input order, batch size and concurrency will be fixed within a comparison. Measurements from a single loop are correlated, so uncertainty will use session/device blocks rather than treat every inference as independent.'),
  p('The predictive analysis will compare core-only release decisions with physical-device outcomes on held-out candidate/device combinations. False acceptance is a core gate pass followed by device failure; false rejection is the reverse. Thresholds will be tuned on development combinations and assessed once on held-out combinations, preserving the distinction between fitting a rule and validating it.'),
 ),
 page('5. Lightweight monitoring and disconnected operation',
  p('The planned monitor will track inference latency histograms, input schema violations, memory pressure, exception categories, model/runtime versions and a bounded sample of confidence or disagreement proxies. It will have explicit CPU, memory, storage and telemetry caps. A proposed starting overhead budget is at most 2% added median latency, subject to task-specific revision before testing.'),
  h('Accuracy is not directly observable without labels'),
  p('Confidence changes, input drift and teacher disagreement may indicate a problem, but they do not establish a drop in task accuracy. The monitor will name them as proxies. Confirmed quality measurements require delayed labels or a controlled local canary set whose coverage is known. A detector that sees only the model output cannot be assumed to distinguish a new valid input distribution from a harmful shift.'),
  p('The study will inject documented changes into authored or licensed test streams: input-scale shifts, missing fields, length changes, runtime failures and resource contention. Detection delay, false-alert rate and overhead will be measured separately. Detector thresholds will be selected on development streams and frozen for a held-out sequence containing both benign changes and harmful degradation.'),
  h('Escalation and rollback'),
  p('A local hard fault, such as incompatible artifacts or repeated inference crashes, can trigger a bounded fallback or rollback according to the release policy. A soft drift alert queues evidence for core review; it does not automatically retrain or replace the model. Centralized review will determine whether more labels, a new calibration set or a new model is appropriate.'),
  p('During disconnection, telemetry will use bounded queues and sequence numbers. Reconnection merges summaries idempotently and records dropped intervals. Fault-injection trials will cover interruption during download, activation and telemetry transfer. Successful recovery must preserve the active version record and avoid duplicate aggregation. A future monitor demonstration will use a simulated stream explicitly labeled as such; no deployed fleet exists in the present project.'),
 ),
 page('6. Roadmap, statistics and reproducibility',
  table(['Phase','Planned work','Exit evidence'],[
   ['A: task/device contract','Select workloads, hardware and owner-approved gates','Frozen task, device and measurement protocols'],
   ['B: reference harness','Pin artifacts; implement paired quality/resource tests','Reproducible baseline and measurement checks'],
   ['C: optimization matrix','Quantize/distill; sweep calibration subsets','Hashes, cost records and validation curves'],
   ['D: device qualification','Run physical trials and held-out gate prediction','Session-level confidence intervals; failure matrix'],
   ['E: edge operations','Build monitor, update slots and bounded telemetry','Overhead, alert and fault-recovery evidence'],
   ['F: release package','Publish source, protocol, measurements and paper','Independent artifact verification/reproduction'],
  ],[103,203,182]),
  p('All candidate failures will remain in the optimization matrix, including conversion errors and unsupported operators. The analysis will report quality-resource Pareto frontiers without cherry-picking only successful models. Repeated comparisons across precision, data size and hardware will be identified as a family; confirmatory hypotheses and exploratory slices will be distinguished.'),
  p('The planned reproduction record contains artifact hashes, source revisions, build commands, calibration/test splits, preprocessing, device identity, measurement scripts, trial order, seeds, thermal/power conditions and raw aggregate observations. Energy measurement precision and baseline subtraction will be stated. Estimated energy from a software counter will not be presented as an external-meter measurement.'),
  p('The strongest validity risks are narrow hardware coverage, nonrepresentative calibration data and delayed or unavailable deployment labels. The first study will therefore make claims only for the tested release tuples and workload distributions. A successful classifier experiment will not validate language generation on a microcontroller, and a core simulator pass will not be labeled physical-device certification.'),
 ),
 page('7. References and expected contribution',
  p('Primary sources consulted October 7, 2026. The methods below motivate candidate optimizations and measurement practice. Published speedups or accuracy results from those papers are not predictions for this project.'),
  ('refs',),
  h('Expected research artifact'),
  p('The planned contribution is a documented path from a core experiment to a defensible device release decision: versioned artifact contracts, paired quality/resource gates, a study of calibration-data requirements and a monitor whose overhead and detection behavior are measured. Negative findings, such as a core metric that fails to predict thermal tail latency, would be valuable evidence about the limits of the pipeline.'),
  p('A future public interface will let readers inspect the release tuple, compare candidate tradeoffs and replay an authored update/rollback scenario. Until implementation begins, the repository and website expose the projected architecture and roadmap. The present paper contains no trained student, quantized artifact, qualified runtime or measured edge result.'),
  note('Current status: Not started. This is an independently authored research proposal, with no implementation or empirical completion claim.'),
 )]
}])
